STORY9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username_attrs = {
    'type': 'text',
    'placeholder':'Username.. '
    }
    email_attrs = {
    'type': 'text',
    'placeholder':'Email..'
    }

    pass1_attrs = {
    'type': 'password',
    'placeholder':'Password..'
    }
    
    pass2_attrs = {
    'type': 'password',
    'placeholder':'Confirm Password..'
    }
    username = forms.CharField(required=True, widget=forms.TextInput(attrs=username_attrs))
    email = forms.EmailField(required=True,widget=forms.TextInput(attrs=email_attrs))
    password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs=pass1_attrs))
    password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs=pass2_attrs))

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import auth, User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm

@login_required(login_url='main:login')
def home(request):
    return render(request, 'main/home.html')

def login(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else :
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
        
            user = auth.authenticate(request, username=username, password=password)
        
            if user is not None:
                auth.login(request,user)
                # print('kelogin')
                return redirect('main:home')
            else :
                messages.info(request, 'Username or Password is incorrect')
    return render(request, 'main/login.html')

def logout(request):
    auth.logout(request)
    return redirect('main:login')

def register(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                # print('berhasil')
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

    context = {'form' : form}
    return render(request, 'main/register.html', context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello!</title>
<style>
    * {
  font-family: "Rubik", sans-serif;
  margin: 0;
box-sizing: border-box;
}
.section1 {
  background-image: linear-gradient(180deg, rgba(0,0,0,0.7122199221485469) 0%, rgba(52,51,69,1) 100%),
    url("/static/img/wall1.jpg");
  height: 100vh;
  -webkit-background-size: cover;
  background-size: cover;
  background-position: center center;
}

.banner-text {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
  color: #dadde4;
  line-height: 0;
}

.banner-text h1 {
  font-size: 100px;
  font-weight: 700;
}
#halo{
  margin-top: -10%;
}

.banner-btn a {
  border: 1px solid #ffffff;
  border-radius: 50px;
  text-decoration: none;
  padding: 10px 30px;
  font-size: 0.8em;
  /* display: inline-block; */
  margin-top: 3em; 
  margin-right: 3em; 
  color: #ffffff;
  /* position:absolute;  */
  float: right;
}

h1 {
  color: #f7aa29;
  font-weight: 600;
  text-align: center;
}

h5 {
  color: #f7aa29;
  font-weight: 600;
  font-size: 30px;
}

li {
  font-weight: 500;
}
.ml9 {
  position: relative;
  font-weight: 200;
  font-size: 4em;
  margin-top: 10%;
}

.ml9 .text-wrapper {
  position: relative;
  display: inline-block;
  /* padding-top: 0.2em; */
  /* padding-right: 0.05em; */
  /* padding-bottom: 0.1em; */
  overflow: hidden;
}

.ml9 .letter {
  transform-origin: 50% 100%;
  display: inline-block;
  line-height: 1em;
}

.arrows {
	width: 80px;
	height: 80px;
	position: absolute;
	left: 50%;
	margin-left: -20px;
	bottom: 20px;
}

.arrows path {
	stroke: #ffffff;
	fill: transparent;
	stroke-width: 3px;	
	animation: arrow 2s infinite;
	-webkit-animation: arrow 2s infinite; 
}

@keyframes arrow
{
0% {opacity:0; transform:translateY(10px)}
80% {opacity:1; transform:translateY(50px)}
100% {opacity:0; transform:translateY(50px)}
}

@-webkit-keyframes arrow /*Safari and Chrome*/
{
0% {opacity:0; transform:translateY(10px)}
80% {opacity:1; transform:translateY(50px)}
100% {opacity:0; transform:translateY(50px)}
}

.arrows path.a1 {
	animation-delay:-0.5s;
	-webkit-animation-delay:-0.5s; /* Safari and Chrome */
}

@media (max-width: 600px) {
  .banner-text h1 {
    font-size: 60px;
  }

  .banner-text h2 {
    font-size: 20px;
  }

  .banner-btn a {
    margin: 10px 10px;
  }
}

.section2 {
  background-color: #343345;
  height: 70vh;
}

.cards-list {
  z-index: 0;
  width: 100%;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
  background-color:#343345;

}

.card {
  margin: 30px auto;
  width: 200px;
  height: 200px;
  border-radius: 40px;
box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
  cursor: pointer;
  transition: 0.4s;
}

.card .card_image {
  width: inherit;
  height: inherit;
  border-radius: 40px;
}

.card .card_image img {
  width: inherit;
  height: inherit;
  border-radius: 40px;
  object-fit: cover;
}

.card .card_title {
  text-align: center;
  border-radius: 0px 0px 40px 40px;
  font-weight: bold;
  font-size: 1.5em;
  margin-top: -130px;
  height: 40px;
}

.card .desc{
  text-align: center;
  font-size: 1em;
}

.card:hover {
  transform: scale(0.9, 0.9);
  box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25), 
    -5px -5px 30px 15px rgba(0,0,0,0.22);
}

.title-white {
  color:#1b2231;
}

@media all and (max-width: 500px) {
  .card{
    width: 150px;
    height: 150px;
  }

  .card .card_title {
    font-size: 1.3em;
  }

  .card .desc{
    font-size: 0.9em;
  }
  .card-list {
    /* On small screens, we are no longer using row direction but column */
    flex-direction: column;
  }
}

</style>
{% endblock meta %}

{% block content %}
<section class="section1">
  <div class="container">
    <p class="banner-btn float-right">
      <a href="{% url 'main:logout' %}" class="active">Log out</a>
    </p>
    <div class="banner-text">
      <div class="text-area" id="halo">
        <h1 style="color: #dadde4;">Hello, </h1>
      </div>
      <h1 class="ml9">
        <span class="text-wrapper">
          <span class="letters">{{request.user}}</span>
        </span>
      </h1>
    </div>
    <svg class="arrows">
      <path stroke-linecap="round" class="a1" d="M0 0 L20 22 L40 0"></path>
    </a>
  </div>
</section>

<section class="section2" id="section2">
  <div class="container justify-content-center align-items-center">
    <br><br><br><br>
      <h1  style="color: #dadde4; font-size:2.7em ">Story of Hilmy</h1>

    <br>
      <div class="cards-list ">
        <div class="card 1">
          <div class="card_image"> <img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/v563-taus-13-gradientsetidea_1.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=7e789fa3fded76029bd5a46418d4c04b" /> </div>
          <a href="http://story1ppwhilmy.herokuapp.com/">
          <div class="card_title title-white">
            <p>Story 1</p>
          </div>
        </a>
        <div class="desc">
          <p>Introduction</p>
        </div>
        
        </div>
        
          <div class="card 2">
          <div class="card_image">
            <img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/v563-taus-07-gradientsetidea_1.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=36d5bf895fadf47fe60ac60cd11f849d" />
            </div>
            <a href="http://story3ppwhilmy.herokuapp.com/">
          <div class="card_title title-white">
            <p>Story 2-5</p>
          </div>
        </a>
        <div class="desc">
          <p>My Own Portfolio + Matcool</p>
        </div>
                
        </div>
        
        <div class="card 3">
          <div class="card_image">
            <img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/v563-taus-10-gradientsetidea_1.jpg?w=1000&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=60ae1921708eba7d7754a47d3f7d5c18" />
          </div>
          <a href="http://story6ppwhilmy.herokuapp.com/">
          <div class="card_title title-white">
            <p>Story 6</p>
          </div>
        </a>
        <div class="desc">
          <p>KegiatanKu.</p>
        </div>
        </div>
          
          <div class="card 4">
          <div class="card_image">
            <img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/v622-kul-04-summergradient_1.jpg?w=1000&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=cf0187d20c228a06fa095da8cf362131" />
            </div>
            <a href="http://story7ppwhilmy.herokuapp.com/">
          <div class="card_title title-white">
            <p>Story 7</p>
          </div>
        </a>
        <div class="desc">
          <p>Accordion</p>
        </div>
          </div>
        
          <div class="card 5">
            <div class="card_image"> <img src="https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/v384-ning-06b-gradientbg_2.jpg?w=1000&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=dfeadb1258fa1fc7a068950feaf274ea" /> 
            </div>
            <a href="http://story8ppwhilmy.herokuapp.com/">
              <div class="card_title title-white">
              <p>Story 8</p>
            </div>
          </a>
          <div class="desc">
            <p>Google API Search</p>
          </div>
          </div>

          <div class="card 6">
            <div class="card_image"> <img src="https://www.shutterstock.com/blog/wp-content/uploads/sites/5/2018/03/Fluorescent-Gradient-Final.jpg" /> 
            </div>
            <a href="https://tk1-covidstudy.herokuapp.com/">
              <div class="card_title title-white">
              <p>TK 1</p>
            </div>
          </a>
          <div class="desc">
            <p>CoronaStudy</p>
          </div>
          </div>
        
          <br><br><br><br>
            <!-- <div class="card 6"> -->
            <!-- <div class="card_image"> -->
              <!-- <img src="https://cdn.blackmilkclothing.com/media/wysiwyg/Wallpapers/PhoneWallpapers_FloralCoral.jpg" /> -->
              <!-- </div> -->
            <!-- <div class="card_title title-white"> -->
              <!-- <p>Card Title</p> -->
            <!-- </div> -->
          <!-- </div> -->
<!--            -->
          <!-- <div class="card 7"> -->
            <!-- <div class="card_image"> -->
              <!-- <img src="https://media.giphy.com/media/10SvWCbt1ytWCc/giphy.gif" /> -->
            <!-- </div> -->
            <!-- <div class="card_title"> -->
              <!-- <p>Card Title</p> -->
            <!-- </div> -->
          <!-- </div> -->
        <!-- </div> -->
  </div>
  
</section>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script type="text/javascript">
    // Wrap every letter in a span
    var textWrapper = document.querySelector('.ml9 .letters');
    textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

    anime.timeline({loop: true})
    .add({
        targets: '.ml9 .letter',
        scale: [0, 1],
        duration: 1500,
        elasticity: 600,
        delay: (el, i) => 45 * (i+1)
      }).add({
        targets: '.ml9',
        opacity: 0,
        duration: 1000,
        easing: "easeOutExpo",
        delay: 1000
      });
    </script>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
<style>
    @import url("https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800;900&display=swap");
    body,
    html {
        margin: 0;
        padding: 0;
        background-image: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)),
        url("/static/img/wall3.jpg");
        height: 100vh;
        -webkit-background-size: cover;
        background-size: cover;
        background-position: center center;
        font-family: "Rubik", sans-serif;
    }
    .user_card {
        width: 25em;
        margin-top: auto;
        margin-bottom: auto;
        background: rgba(209, 209, 209, 0.486);
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        border-radius: 3em;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title{
        color:  #dadde4;
        font-size: 2.3em;
        font-weight: 800;
    }

    .login_btn {
        width: 50%;
        background:#f7aa29!important;
        color: white !important;
        border-radius: 1.5em;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }
    .input-group-text {
        background: #f7aa29 !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

    #messages{
        background-color: grey;
        color: #fff;
        padding: 10px;
        margin-top: 10px;
    }
</style>
{% endblock meta %}

{% block content %}
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center mt-3">
                <h3 id="form-title">Login</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                    
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn login_btn" type="submit" value="Login">
                           </div>
                </form>
            </div>

            {%for message in messages%}
            <div class="alert alert-danger d-flex justify-content-center mt-3" role="alert" style="font-size: 0.8em;">
                {{message}}
            </div>
            {%endfor%}

            <div class="mt-4 mb-3">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'main:register' %}" class="ml-2" style="color: #f7ba5b;">Sign Up</a>
                </div>
        </div>
        </div>
    </div>
</div>
  
{% endblock content %}

main/templates/main/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
<style>
    body,
    html {
        margin: 0;
        padding: 0;
        background-image: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)),
        url("/static/img/wall2.jpg");
        height: 100vh;
        -webkit-background-size: cover;
        background-size: cover;
        background-position: center center;
        font-family: "Rubik", sans-serif;
    }
    .user_card {
        width: 30em;
        margin-top: auto;
        margin-bottom: auto;
        background: rgba(209, 209, 209, 0.486);
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        /* box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
        /* -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
        /* -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
        border-radius: 3em;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title{
        color:  #dadde4;
        font-size: 2.3em;
        font-weight: 800;
    }
    .login_btn {
        width: 100%;
        background:#f7aa29!important;
        color: white !important;
        border-radius: 1.5em;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }

    .input-group{
        font-size: 1em;
    }
    .input-group-text {
        background: #f7aa29 !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

</style>
{% endblock meta %}

{% block content %}

<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center mt-3">
                <h3 id="form-title">Register</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{form.username}}
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{form.email}}
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{form.password1}}
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{form.password2}}
                    </div>

                       <div class="d-flex justify-content-center mt-4 login_container">
                         <input class="btn login_btn" type="submit" value="Register Account">
                       </div>
                </form>
            </div>

            {% if form.errors %}
            <div class="alert alert-warning  d-flex justify-content-center mt-4 " role="alert">
                {{form.errors}}
              </div>
            {% endif %}
            
            {%for message in messages%}
                <div class="alert alert-success  d-flex justify-content-center mt-4" role="alert">
                    {{message}}
                </div>
            {%endfor%}

            <div class="mt-4 mb-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'main:login' %}" class="ml-2" style="color: #f7ba5b;">Sign In</a>
                </div>
        </div>
        </div>
    </div>
</div>
  
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>